### PR TITLE
Fix: Resolve peer dependencies

### PR DESCRIPTION
**Pull request by kennythepark**
`npm i` fails with peer-dependency related issues. 

**Changes:**
- Bump `nextjs-progressbar` to `0.0.13` for dependency check with React v17
- Remove unused `react-image-palette`
- Replace `react-use-system-theme` (unmaintained, out-of-sync peer dependency wise) with `react-use-system-color-mode`

### CODE REVIEW

**Comment by kennythepark** [comment]
@danielcolinjames I haven't committed the package lock since if our npm / node versions are probably different and that'll make the lock files to go crazy. Let me know what the project's preferred npm / node versions are and I'll update accordingly.

**Comment by danielcolinjames** [comment]
nice!! I haven't tried installing the project fresh recently to make sure it's easy to get up and running—I should definitely do that. lots of things to do to make this more contributor friendly

I've been using yarn lately instead of npm, but no strong preference either way. there might even be both yarn-lock and package-lock files in here haha, the codebase is kind of a mess

this repo has been a very "only I will see this code" type of project so far so apologies in general for the mess 😂

**Comment by danielcolinjames** [comment]
so I just tried running `yarn` from a fresh git clone, I guess yarn is more forgiving because it ran okay! 😆  TIL

but this is probably good to merge anyway

**Review by danielcolinjames — APPROVED** [review]
🙌

**Pull request merged**
